export const BASE_API_URL = 'https://api.tvmaze.com/'

//This is the list based on the documentation of tvmaze. https://www.tvmaze.com/faq/32/genre-definitions
export const TVMAZE_GENRES = [
  'Action',
  'Adult',
  'Adventure',
  'Anime',
  'Children',
  'Comedy',
  'Crime',
  'DIY',
  'Drama',
  'Espionage',
  'Family',
  'Fantasy',
  'Food',
  'History',
  'Horror',
  'Legal',
  'Medical',
  'Music',
  'Mystery',
  'Nature',
  'Romance',
  'Science-Fiction',
  'Sports',
  'Supernatural',
  'Thriller',
  'Travel',
  'War',
  'Western',
] as const
